# if-endif補完
[[plugins]]
repo = 'tpope/vim-endwise'

# リファレンス表示 K
[[plugins]]
repo = 'thinca/vim-ref'

# クオート切り替え cs'" cs"' cs'<p>
[[plugins]]
repo = 'tpope/vim-surround'

# コメント拡張 Ctrl --
[[plugins]]
repo = 'tomtom/tcomment_vim'

# 文末スペース表示
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# 編集履歴表示->ファイルオープン :MRU
[[plugins]]
repo = 'yegappan/mru'

# 括弧自動閉じ
[[plugins]]
repo = 'Townk/vim-autoclose'

# html補完 Ctrl y,
[[plugins]]
repo = 'mattn/emmet-vim'

# grep拡張
[[plugins]]
repo = 'grep.vim'

# 癒し
[[plugins]]
repo = 'drillbits/nyan-modoki.vim'

# elixirシンタックス
[[plugins]]
repo = 'elixir-lang/vim-elixir'

# シンタックスチェック
[[plugins]]
repo = 'scrooloose/syntastic'

# coffeeシンタックス
[[plugins]]
repo = 'kchmck/vim-coffee-script'

# for Markdown
[[plugins]]
repo = 'kannokanno/previm'
[[plugins]]
repo = 'tyru/open-browser.vim'
