# if-endif補完
[[plugins]]
repo = 'tpope/vim-endwise'

# リファレンス表示 K
[[plugins]]
repo = 'thinca/vim-ref'

# クオート切り替え cs'" cs"' cs'<p>
[[plugins]]
repo = 'tpope/vim-surround'

# コメント拡張 Ctrl --
[[plugins]]
repo = 'tomtom/tcomment_vim'

# 文末スペース表示
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# 編集履歴表示->ファイルオープン :MRU
[[plugins]]
repo = 'yegappan/mru'

# 括弧自動閉じ
[[plugins]]
repo = 'Townk/vim-autoclose'

# html補完 Ctrl y,
[[plugins]]
repo = 'mattn/emmet-vim'

# grep拡張
[[plugins]]
repo = 'vim-scripts/grep.vim'

# elixirシンタックス
[[plugins]]
repo = 'elixir-lang/vim-elixir'

# シンタックスチェック (非同期)
[[plugins]]
repo = 'w0rp/ale'

# coffeeシンタックス
[[plugins]]
repo = 'kchmck/vim-coffee-script'

# Markdownプレビュー Po
[[plugins]]
repo = 'kannokanno/previm'

# ブラウザ検索 Bo
[[plugins]]
repo = 'tyru/open-browser.vim'

# Git差分表示
[[plugins]]
repo = 'airblade/vim-gitgutter'

# Dockerfileシンタックス
[[plugins]]
repo = 'ekalinin/Dockerfile.vim'

# ステータスライン オシャレ
[[plugins]]
repo = 'itchyny/lightline.vim'

# クイックハイライト
[[plugins]]
repo = 't9md/vim-quickhl'

# CSV色分け
[[plugins]]
repo = 'mechatroner/rainbow_csv'
